using System;
using Alchemy.Server;
using System.Net;
using Alchemy.Server.Classes;
using log4net;
using RCAT;
using Newtonsoft.Json;

namespace Proxy
{
    public class ClientServer
    {

        WSServer clientListener = null;

        protected void RegisterProxyMethods()
        {
            Proxy.broadcastToClients = BroadcastToClients;
        }

        public ClientServer(ILog log)
        {
            RegisterProxyMethods();
            // Client server uses Alchemy Websockets
            clientListener = new WSServer(81, IPAddress.Any);
            clientListener.Log.Logger.IsEnabledFor(log4net.Core.Level.Debug);
            clientListener.DefaultOnReceive = new OnEventDelegate(OnReceive);
            clientListener.DefaultOnSend = new OnEventDelegate(OnSend);
            clientListener.DefaultOnConnect = new OnEventDelegate(OnConnect);
            clientListener.DefaultOnDisconnect = new OnEventDelegate(OnDisconnect);
            clientListener.TimeOut = new TimeSpan(0, 5, 0);

            clientListener.Start();
        }

        // Events generated by client connections
        public static void OnConnect(UserContext AContext)
        {
            Console.WriteLine("Client Connection From : " + AContext.ClientAddress.ToString());

            User me = new User();
            me.Name = AContext.ClientAddress.ToString();
            me.Context = AContext;

            Proxy.onlineUsers.Add(me.Name, me.Context);
            Proxy.sendClientConnectToServer(AContext);
        }

        public static void OnReceive(UserContext AContext)
        {
            Console.WriteLine("Client data Received From : " + AContext.ClientAddress.ToString());
            User me = new User();
            me.Name = AContext.ClientAddress.ToString();
            me.Context = AContext;

            string json = AContext.DataFrame.ToString();
            Position pos = JsonConvert.DeserializeObject<Position>(json);

            me.pos = pos;

            Proxy.sendSetPositionToServer(me);

        }

        public static void OnSend(UserContext AContext)
        {
            Console.WriteLine("Data Send To : " + AContext.ClientAddress.ToString() + " | " + AContext.DataFrame.ToString());
        }

        public static void OnDisconnect(UserContext AContext)
        {
            Console.WriteLine("Client Disconnected : " + AContext.ClientAddress.ToString());

            Proxy.onlineUsers.Remove(AContext.ClientAddress.ToString());
            Proxy.sendClientDisconnectToServer(AContext);
        }

        public void Stop()
        {
            clientListener.Stop();
        }

        public void BroadcastToClients(ClientBroadcast broadcast)
        {
            foreach (string client in broadcast.clients)
            {
                UserContext cl = Proxy.onlineUsers[client];
                cl.Send(broadcast.data);
            }
        }
    }
}
