using System;
using System.Text;
using System.Net.Sockets;
using System.Threading;
using System.Net;
using log4net;
using RCAT;
using System.Collections.Generic;
using Alchemy.Server.Classes;

namespace Proxy
{
    public class GameServer
    {
        protected static TcpListener serverListener = null;

        protected List<ServerContext> onlineServers = new List<ServerContext>();
        protected Dictionary<string, ServerContext> clientPerServer = new Dictionary<string, ServerContext>();

        protected int roundrobin = 0;

        public static ILog Log;

        public int serverPort = 82;

        protected void RegisterProxyMethods()
        {
            Proxy.sendSetPositionToServer = Send;
            Proxy.sendClientDisconnectToServer = SendClientDisconnect;
            Proxy.sendClientConnectToServer = SendClientConnect;
        }

        public GameServer(ILog log)
        {
            // Servers register their existence and communicate with proxy through TCP
            Log = log;
            RegisterProxyMethods();

            if (serverListener == null)
            {
                try
                {
                    serverListener = new TcpListener(IPAddress.Any, serverPort);
                    ThreadPool.QueueUserWorkItem(serverListen, null);
                }
                catch { Log.Error("Game Server failed to start"); }
            }

            // Accept commands on the console and keep it alive
        }

        protected void serverListen(object State)
        {
            serverListener.Start();
            while (serverListener != null)
            {
                try
                {
                    serverListener.BeginAcceptTcpClient(RunServer, null);
                }
                catch {/* Ignore */ }
            }
        }

        protected void RunServer(IAsyncResult AResult)
        {
            // Server connection
            TcpClient TcpConnection = null;
            try
            {
                if (serverListener != null)
                    TcpConnection = serverListener.EndAcceptTcpClient(AResult);
            }
            catch (Exception e) { Log.Error("Connect Failed", e); }

            if (TcpConnection != null)
            {
                using (ServerContext SContext = new ServerContext())
                //each server has its own context
                {
                    SContext.gameServer = this;
                    SContext.serverConnection = TcpConnection;
                    SContext.ClientAddress = SContext.serverConnection.Client.RemoteEndPoint;
                    onlineServers.Add(SContext);
                    try
                    {
                        while (SContext.serverConnection.Connected)
                        {
                            SContext.serverConnection.Client.BeginReceive(SContext.Buffer, 0, SContext.Buffer.Length, SocketFlags.None, new AsyncCallback(DoReceive), SContext);
                        }
                    }
                    catch (Exception e) { Log.Error("Game Server Forcefully Disconnected", e); }
                }
            }
        }

        // Events generated by servers connecting to proxy
        private void DoReceive(IAsyncResult AResult)
        {
            ServerContext SContext = (ServerContext)AResult.AsyncState;
            int received = 0;

            try
            {
                received = SContext.serverConnection.Client.EndReceive(AResult);
            }
            catch (Exception e) { Log.Error("[GAMESERVER]: Game Server Forcefully Disconnected", e); }

            // TODO: No packets bigger then BufferSize are allowed at this time
            if (received > 0)
            {
                SContext.sb.Append(UTF8Encoding.UTF8.GetString(SContext.Buffer, 0, received));
                HandleRequest(SContext);
                if (received == SContext.BufferSize)
                {
                    throw new Exception("[GAMESERVER]: HTTP Connect packet reached maximum size. FIXME!!");
                }
            }
            else
            {
                onlineServers.Remove(SContext);
                SContext.Dispose();
            }
        }

        // Handles the server request. Broadcast is the only server side functionality at this point. 
        protected void HandleRequest(ServerContext server)
        {
            ClientBroadcast message = Newtonsoft.Json.JsonConvert.DeserializeObject<ClientBroadcast>(server.sb.ToString());
            Proxy.broadcastToClients(message);
        }

        // Sends client data to the server
        public void Send(User client)
        {

        }

        public void SendClientConnect(UserContext client)
        {
            ServerContext server = PickServer();
            clientPerServer.Add(client.ClientAddress.ToString(), server);
            
            ClientConnection conn;
            conn.client = client.ClientAddress.ToString();
            conn.connected = true;

            server.Send(UTF8Encoding.UTF8.GetBytes(Newtonsoft.Json.JsonConvert.SerializeObject(conn)));
        }

        protected ServerContext PickServer()
        {
            ServerContext server =  onlineServers[roundrobin];
            roundrobin++;
            if (roundrobin == onlineServers.Count)
                roundrobin = 0;
            return server;
        }

        public void SendClientDisconnect(UserContext client)
        {
            ServerContext server = clientPerServer[client.ClientAddress.ToString()];
            clientPerServer.Remove(client.ClientAddress.ToString());
            
            ClientConnection conn;
            conn.client = client.ClientAddress.ToString();
            conn.connected = false;

            server.Send(UTF8Encoding.UTF8.GetBytes(Newtonsoft.Json.JsonConvert.SerializeObject(conn)));
        }

        public void Stop()
        {
            serverListener.Stop();
        }
    }
}
